import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faArrowLeft,
    faArrowRight,
    faUpRightFromSquare,
    faArrowRightFromBracket,
    faPlus,
    faNewspaper,
    faFileWord,
    faFile,
    faChartLine,
    faBookOpen,
    faCircleExclamation,
    faBuilding,
    faCalendar,
    faCheck,
    faCircleCheck,
    faChevronLeft,
    faChevronRight,
    faXmark,
    faTrash,
    faDownload,
    faUpload,
    faFilePdf,
    faClockRotateLeft,
    faHistory,
    faLightbulb,
    faLock,
    faLockOpen,
    faBell,
    faBellSlash,
    faMagnifyingGlass,
    faGavel,
    faHeadphones,
    faPlay,
    faPlayCircle,
    faSpinner,
    faCircleNotch,
    faGraduationCap,
    faSchool,
    faBriefcase,
    faCartShopping,
    faCartFlatbed,
    faRobot,
    faEnvelope,
    faPaperPlane,
    faCommentDots,
    faFileArrowDown,
    faFileArrowUp,
    faExpand,
    faCircleInfo,
    faBook,
    faFolder,
    faFolderOpen,
    faHeadset,
    faSquarePlus,
    faListCheck,
    faShoppingBag,
    faCircleQuestion,
    faHourglass,
    faStar,
    faCreditCard,
    faUser,
    faMicrophone,
    faKeyboard,
    faSignal,
    faMapPin,
    faStethoscope,
    faTable,
    faQuoteLeft,
    faFire,
    faBullseye,
    faThumbsUp,
    faThumbsDown,
    faEye,
    faBullhorn,
    faTrophy,
    faReceipt,
    faGear,
    faLink,
    faHammer,
    faList,
} from '@fortawesome/free-solid-svg-icons';
import {
    faShieldCheck,
    faTimer,
} from '@fortawesome/pro-solid-svg-icons';

// Local definition for the 'arrow-up-right' icon (Font Awesome classic solid)
const faArrowUpRight: IconDefinition = {
    prefix: 'fas',
    iconName: 'arrow-up-right' as any,
    icon: [384, 512, [], 'e09f', 'M384 96c0-17.7-14.3-32-32-32L128 64c-17.7 0-32 14.3-32 32s14.3 32 32 32L274.7 128 9.4 393.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L320 173.3 320 320c0 17.7 14.3 32 32 32s32-14.3 32-32l0-224z'],
};

const iconMap: Record<string, IconDefinition> = {
    arrow_back: faArrowLeft,
    arrow_forward: faArrowRight,
    arrow_outward: faArrowUpRight,
    logout: faArrowRightFromBracket,
    add: faPlus,
    article: faNewspaper,
    assignment: faFileWord,
    assessment: faChartLine,
    auto_stories: faBookOpen,
    bolt: faCircleExclamation,
    business: faBuilding,
    calendar_today: faCalendar,
    card_membership: faShieldCheck,
    check: faCheck,
    check_circle: faCircleCheck,
    chevron_left: faChevronLeft,
    chevron_right: faChevronRight,
    close: faXmark,
    delete: faTrash,
    description: faFileWord,
    download: faDownload,
    edit_note: faFileWord,
    error_outline: faCircleExclamation,
    event: faCalendar,
    event_busy: faCalendar,
    expand_more: faChevronRight,
    explore: faMagnifyingGlass,
    forum: faCommentDots,
    gavel: faGavel,
    headphones: faHeadphones,
    history: faHistory,
    history_edu: faGraduationCap,
    info: faCircleInfo,
    lightbulb: faLightbulb,
    lock: faLock,
    lock_open: faLockOpen,
    notifications: faBell,
    notifications_none: faBellSlash,
    open_in_new: faArrowRightFromBracket,
    picture_as_pdf: faFilePdf,
    play_arrow: faPlay,
    play_circle: faPlayCircle,
    progress_activity: faSpinner,
    quiz: faCircleQuestion,
    schedule: faTimer,
    school: faSchool,
    search: faMagnifyingGlass,
    search_off: faMagnifyingGlass,
    send: faPaperPlane,
    shopping_bag: faCartFlatbed,
    shopping_cart: faCartShopping,
    smart_toy: faRobot,
    trending_up: faChartLine,
    verified: faShieldCheck,
    work: faBriefcase,
    priority_high: faCircleExclamation,
    star: faStar,
    map_pin: faMapPin,
    person: faUser,
    notes: faBook,
    mic: faMicrophone,
    credit_card: faCreditCard,
    menu_book: faBookOpen,
    local_fire_department: faFire,
    track_changes: faBullseye,
    thumb_up: faThumbsUp,
    thumb_down: faThumbsDown,
    chat_bubble_outline: faCommentDots,
    visibility: faEye,
    tips_and_updates: faLightbulb,
    upload_file: faUpload,
    replay: faClockRotateLeft,
    settings: faGear,
    campaign: faBullhorn,
    emoji_events: faTrophy,
    receipt_long: faReceipt,
    help_outline: faCircleQuestion,
    spellcheck: faCheck,
    link: faLink,
    construction: faHammer,
    calendar_month: faCalendar,
    view_list: faList,
    compare: faChartLine,
};

export interface IconProps {
    icon: string;
    className?: string;
    style?: React.CSSProperties & Record<string, any>;
}

export const Icon: React.FC<IconProps> = ({ icon, className = '', style }) => {
    const faIcon = iconMap[icon] || iconMap['description'] as any;

    if (!faIcon) {
        return <FontAwesomeIcon icon={faFile} className={className} style={style as any} />;
    }

    return (
        <FontAwesomeIcon
            icon={faIcon}
            className={className}
            style={style as any}
        />
    );
};

export {
    faArrowLeft,
    faArrowRight,
    faPlus,
    faCheck,
    faXmark,
    faTrash,
    faDownload,
    faUpload,
    faCalendar,
    faChevronLeft,
    faChevronRight,
    faMagnifyingGlass,
    faHistory,
    faLightbulb,
    faLock,
    faBell,
    faPlay,
    faSpinner,
    faBook,
    faSchool,
    faBriefcase,
    faBuilding,
    faGavel,
    faHeadphones,
    faChartLine,
    faShoppingBag,
    faFilePdf,
    faPlayCircle,
    faEnvelope,
    faPaperPlane,
    faCommentDots,
    faNewspaper,
    faCircleCheck,
    faCircleExclamation,
    faSquarePlus,
    faExpand,
    faShieldCheck,
    faGraduationCap,
    faRobot,
    faTimer,
    faListCheck,
    faFolder,
    faFolderOpen,
    faHeadset,
    faFileWord,
    faBookOpen,
    faLockOpen,
    faBellSlash,
    faClockRotateLeft,
    faCircleInfo,
    faCartFlatbed,
    faCartShopping,
    faStar,
    faCreditCard,
    faUser,
    faMicrophone,
    faKeyboard,
    faMapPin,
    faStethoscope,
    faTable,
    faQuoteLeft,
    faFire,
    faBullseye,
    faThumbsUp,
    faThumbsDown,
    faEye,
    faBullhorn,
    faTrophy,
    faReceipt,
    faGear,
    faLink,
    faHammer,
    faList,
};